Update __init__.py
When I ran the code, I encountered the following error:

ModuleNotFoundError: No module named 'importlib.metadata'.

This happened because the correct module name is importlib_metadata. To fix the issue, I updated the _init_.py file to use importlib_metadata instead.